version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unistalker-web
    ports:
      - "8000:8000"
    volumes:
      - ./backend/logs:/app/backend/logs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
